# Generated by Django 2.2.10 on 2020-03-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='welcome_text',
            field=models.TextField(default='WELCOME', max_length=200),
        ),
    ]
