# Generated by Django 2.2.10 on 2020-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_settings_welcome_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='logged_in_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('logged_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
