# Generated by Django 2.2.10 on 2020-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_logged_in_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.TextField(max_length=200, null=True)),
                ('key', models.TextField(max_length=200, null=True)),
                ('issue_type', models.TextField(max_length=200, null=True)),
                ('project', models.TextField(max_length=200, null=True)),
                ('priority', models.TextField(max_length=200, null=True)),
                ('summary', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('assignee', models.TextField(max_length=200, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
