# Generated by Django 2.1.7 on 2020-03-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_ticket_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_list',
            old_name='description',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='ticket_list',
            old_name='issue_id',
            new_name='suplier',
        ),
        migrations.RenameField(
            model_name='ticket_list',
            old_name='issue_type',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='ticket_list',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket_list',
            name='project',
        ),
    ]
