# Generated by Django 2.1.7 on 2020-04-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200320_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_list',
            name='iconurl',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
